
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.ComboBoxEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Admin
 */
public class MainMessenger extends javax.swing.JFrame {

    /**
     * Creates new form MainMessenger
     */
    public MainMessenger() {
        initComponents();
        setResizable(false);
        setTitle(" Messenger");
        this.setLocationRelativeTo(null);

        adminUsuaurios ap = new adminUsuaurios("./Users.txt");
        ap.cargarArchivo();

        for (Usuario p : ap.getPersonitas()) {
            personas.add(p);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_registrarse = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        tf_display = new javax.swing.JTextField();
        j_calendario = new com.toedter.calendar.JDateChooser();
        tf_pass = new javax.swing.JPasswordField();
        bt_registrar = new javax.swing.JButton();
        bt_regresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        perfil = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        tf_metodos = new javax.swing.JTextField();
        bt_enviar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_dis = new javax.swing.JTextField();
        tf_paas = new javax.swing.JPasswordField();
        bt_in = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lb_regis = new javax.swing.JLabel();
        bt_exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jd_registrarse.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Nombre");
        jd_registrarse.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        jLabel5.setText("Contraseña");
        jd_registrarse.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jLabel6.setText("Display Name");
        jd_registrarse.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, 30));

        jLabel7.setText("Fecha de nacimiento");
        jd_registrarse.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));
        jd_registrarse.getContentPane().add(tf_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 130, -1));
        jd_registrarse.getContentPane().add(tf_display, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 180, 130, -1));
        jd_registrarse.getContentPane().add(j_calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 130, -1));
        jd_registrarse.getContentPane().add(tf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 130, -1));

        bt_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/forms.png"))); // NOI18N
        bt_registrar.setContentAreaFilled(false);
        bt_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarMouseClicked(evt);
            }
        });
        jd_registrarse.getContentPane().add(bt_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 80, 70));

        bt_regresar.setText("Regresar");
        bt_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_regresarMouseClicked(evt);
            }
        });
        jd_registrarse.getContentPane().add(bt_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 90, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jd_registrarse.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 490));

        perfil.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        area1.setColumns(20);
        area1.setRows(5);
        jScrollPane1.setViewportView(area1);

        perfil.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 520, 330));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        perfil.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 210, 330));
        perfil.getContentPane().add(tf_metodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 510, 100));

        bt_enviar.setText("Enviar");
        bt_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_enviarActionPerformed(evt);
            }
        });
        perfil.getContentPane().add(bt_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 170, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        perfil.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel11.setText("Display name");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 120, 50));

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel12.setText("Contraseña");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 120, 70));
        getContentPane().add(tf_dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 120, 40));
        getContentPane().add(tf_paas, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 120, 40));

        bt_in.setBackground(new java.awt.Color(0, 204, 0));
        bt_in.setText("Ingresar");
        bt_in.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_inMouseClicked(evt);
            }
        });
        getContentPane().add(bt_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 110, 40));

        jLabel2.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        jLabel2.setText("No tienes cuenta?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, -1, -1));

        lb_regis.setFont(new java.awt.Font("MS PGothic", 1, 14)); // NOI18N
        lb_regis.setForeground(new java.awt.Color(0, 51, 255));
        lb_regis.setText("Click here");
        lb_regis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_regisMouseClicked(evt);
            }
        });
        getContentPane().add(lb_regis, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, -1));

        bt_exit.setText("Salir");
        getContentPane().add(bt_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 70, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_regisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_regisMouseClicked
        jd_registrarse.pack();
        jd_registrarse.setModal(true);
        jd_registrarse.setLocationRelativeTo(this);
        jd_registrarse.setVisible(true);
    }//GEN-LAST:event_lb_regisMouseClicked

    private void bt_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_regresarMouseClicked
        jd_registrarse.setVisible(false);
    }//GEN-LAST:event_bt_regresarMouseClicked

    private void bt_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarMouseClicked
        String nombre = tf_user.getText();
        String password = tf_pass.getText();
        String display = tf_display.getText();
        String calendario = j_calendario.getDate().toString();
        personas.add(new Usuario(nombre, password, display, calendario));
        adminUsuaurios ap = new adminUsuaurios("./Users.txt");
        //ap.cargarArchivo();
        Usuario p = new Usuario(nombre, password, display, calendario);
        ap.getPersonitas().add(p);
        try {
            ap.escribirArchivo();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

        JOptionPane.showMessageDialog(this, " Ha sido registrado exitosamente");

        tf_user.setText("");
        tf_pass.setText("");
        tf_display.setText("");
        //correoClient.setText("");


    }//GEN-LAST:event_bt_registrarMouseClicked

    private void bt_inMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_inMouseClicked
        String dis = tf_dis.getText();
        String pas = tf_paas.getText();
        boolean entrar = false;
        tf_metodos.setText(dis + ": ");
        for (int i = 0; i < personas.size(); i++) {
            if (personas.get(i).getDisplay().equals(dis) && personas.get(i).getPassword().equals(pas)) {
                JOptionPane.showMessageDialog(this, " Bienvenido " + dis);
                perfil.pack();
                perfil.setModal(true);
                perfil.setLocationRelativeTo(this);
                perfil.setVisible(true);

                entrar = true;
                // flag = i;
                tf_dis.setText("");
                tf_paas.setText("");

                break;

            }

        }
        //  System.out.println(entrar);

        if (entrar == false) {
            JOptionPane.showMessageDialog(this, " Usuario y/o contraseña ");
            tf_display.setText("");
            tf_pass.setText("");
        }
    }//GEN-LAST:event_bt_inMouseClicked

    private void bt_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_enviarActionPerformed
        String cadena = tf_metodos.getText();
        metodosCadena m = new metodosCadena();
        int pos = cadena.indexOf(':');// uso del index of para saber su posicion y asi poder usar el metodo de substring
        String nueva = cadena.substring(pos + 2, cadena.length());
        String neww = cadena.substring(pos + 2, cadena.length() - 1);
        if (nueva.length() < 13) {
            JOptionPane.showMessageDialog(null, "La cadena debe de ser mayor a 13");
        } else if (nueva.length() >= 13 && nueva.charAt(nueva.length() - 1) == '1') {
            JOptionPane.showMessageDialog(null, "entro a la opcion1");
            String nueva2 = m.concatenado(neww);
            area1.setText("Usuario: " + neww + "\n" + "Maquina: " + nueva2);

        } else if (nueva.length() >= 13 && nueva.charAt(nueva.length() - 1) == '2') {
            JOptionPane.showMessageDialog(null, "entro a la opcion2");
            String nn = m.ReplaceAscii(neww);
            //m.ReplaceAscii(nueva);
            area1.setText("Usuario: " + neww + "\n" + "Maquina: " + nn + " ");

        } else if (nueva.length() >= 13 && nueva.charAt(nueva.length() - 1) == '3') {
            JOptionPane.showMessageDialog(null, "entro a la opcion 3");
            String nueva2 = m.patron3(neww);
            area1.setText("Usuario: " + neww + "\n" + "Maquina: " + nueva2);
        } else if (nueva.length() >= 13 && nueva.charAt(nueva.length() - 1) == '4') {
            JOptionPane.showMessageDialog(null, "entro a la opcion 4");
        } else {
            JOptionPane.showMessageDialog(null, "La cadena no posee ningun numero dentro del rango solicitado");
        }

    }//GEN-LAST:event_bt_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMessenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMessenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMessenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMessenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMessenger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area1;
    private javax.swing.JButton bt_enviar;
    private javax.swing.JButton bt_exit;
    private javax.swing.JButton bt_in;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JButton bt_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser j_calendario;
    private javax.swing.JDialog jd_registrarse;
    private javax.swing.JLabel lb_regis;
    private javax.swing.JDialog perfil;
    private javax.swing.JTextField tf_dis;
    private javax.swing.JTextField tf_display;
    private javax.swing.JTextField tf_metodos;
    private javax.swing.JPasswordField tf_paas;
    private javax.swing.JPasswordField tf_pass;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables
   ArrayList<Usuario> personas = new ArrayList();

}
